namenode:
  image: sfedyakov/hadoop-271-cluster 
  container_name: namenode
  hostname: namenode
  ports:
    - "8088:8088"
    - "50090:50090"
    - "19888:19888"
  command: "/etc/bootstrap.sh -d -namenode"

datanode1:
  image: sfedyakov/hadoop-271-cluster
  container_name: datanode1
  links:
    - "namenode:namenode"
#  ports:
#    - "50070:50070"
  hostname: datanode1
  dns: "namenode"
  command: "/etc/bootstrap.sh -d -datanode"

datanode2:
  image: sfedyakov/hadoop-271-cluster
  container_name: datanode2
  links:
    - "namenode:namenode"
#  ports:
#    - "50070:50070"
  hostname: datanode2
  dns: "namenode"
  command: "/etc/bootstrap.sh -d -datanode"

datanode3:
  image: sfedyakov/hadoop-271-cluster
  container_name: datanode3
  links:
    - "namenode:namenode"
#  ports:
#    - "50070:50070"
  hostname: datanode3
  dns: "namenode"
  command: "/etc/bootstrap.sh -d -datanode"

